#!/usr/bin/ruby

PRINT_ENABLED = true
#何回オークションするか
AUCTION_COUNT = 6
#一回のオークションでどれぐらい割引率が下がるか1.0で10%
DISCOUNT_RATIO_PER_AUCTION = 1.0

POINT_PER_PRICE = 0.109

PLAYER_NUM=4
PLAYER_BUDGET=100
TEST_GAME_COUNT=500
